POST  http://localhost:5000/api/Account/Login
content-type: application/json
cache-control: no-cache

{
    "Email": "dariovoll+4@gmail.com",
    "Password": "Kartofl169-"
}


###

POST  http://localhost:5000/api/account/register
content-type: application/json
cache-control: no-cache

{
    "Email": "da",
    "Password": "da1234A"
}

###

GET http://localhost:5000/api/scheme
content-type: application/json
cache-control: no-cache
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXJpb3ZvbGwrNEBnbWFpbC5jb20iLCJqdGkiOiI3MTY4YjU1Ni01N2Y4LTQ3NzEtYjY3YS1hODAwMWI1ZmE5NjkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImM5Mjc1NWM3LTljMzUtNGQ5OC04OTMxLWRlZjA3MzE4OWIwYiIsImV4cCI6MTUyMzAzMDU1OCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.lNpS8cFbrsbqFVnOkt1nGdBBaGdYT-nsk1DA7ix_Lt8


